#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Create the index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Get the hostname
hostname=$(hostname)

# Code to configure redirect for a single page (/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By $hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=rpaonSDPw7Y permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the web server after updating the settings
sudo service nginx restart
