#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Create the index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Get the hostname
hostname=$(hostname)

# Add custom header to display hostname
sudo sed -i "/server_name _;/a \\n\tadd_header X-Served-By $hostname;" /etc/nginx/sites-enabled/default

# Configure redirect for a single page (/redirect_me)
sudo sed -i "/server_name _;/a \\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=rpaonSDPw7Y permanent;" /etc/nginx/sites-enabled/default

# Configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the web server after updating the settings
sudo service nginx restart
