#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend maskfacedcoder
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 6113-web-01 34.228.12.95:80 check
    server 6113-web-02 	34.229.14.101:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /
    stats hide-version
    stats auth admin:admin
EOL

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

