#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=rpaonSDPw7Y permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx reload
