#!/usr/bin/env bash
# This script sets up a 301 redirection on an Nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
REDIRECT_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
"
echo "$REDIRECT_CONFIG" | sudo tee /etc/nginx/sites-available/default
sudo service nginx reload
